#!/usr/bin/env bash
# Transfer a file into a server given a
# file, user, IP and path to tranfers
if [ $# -lt 3 ];
    then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -i "$4" "$1" "$3"@"$2":~/
fi
