#!/usr/bin/env bash
# Transfer a file into a server given a
# file, user, IP and path to tranfers
if [ $# -ne 4 ];
    then echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
