#!/usr/bin/env bash                                                                                                                                                                
# Set up a Nginx web server and add header X-Served-By  
# shellcheck disable=SC2086                                                                                                                         
apt update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/error404.html
sed -i '/listen 80 default_server/a error_page 404 /error404.html;\nlocation =  /error404.html {\n\troot /var/www/html/;\n\tinternal;\n}' /etc/nginx/sites-available/default
NAME=$(hostname)
sed -i '/listen 80 default_server/a add_header X-Served-By '$NAME';' /etc/nginx/sites-available/default
sudo service nginx restart
