#!/usr/bin/env bash
# Scripts that make a mysql dump with all databases and create a tar file with format %d-%m-%Y
sudo mysqldump -u root --password="$1" --all-databases > backup.sql
DATE=$(date +%d-%m-%Y)
sudo tar -zcvf "$DATE".tar.gz backup.sql
