#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes
# display hours from 0 to 12
# display minutes from 1 to 59
i=0
j=1
while ((i <= 12)); do
    echo Hour: "$i"
    while ((j <= 59)); do
        echo "$j"
        ((j++))
    done
    j=1
    ((i++))
done