#!/usr/bin/env bash
# Bash script that gives you information about the school file
if [ ! -e school ];
then
    echo school file does not exist
    exit 0
fi

echo school file exists

if test -s school;
then
    echo school file is not empty
else
    echo school file is empty
fi

if test -f school;
then
    echo school is a regular file
fi
