#!/usr/bin/env bash
# Bash script that configures an Ubuntu server with the below requirements
cp /etc/hosts ~/hosts.new
sed -i "s/.*localhost$/127.0.0.1       localhost/g" ~/hosts.new
sed -i "s/.*facebook.com//g" ~/hosts.new
cat ~/hosts.new > /etc/hosts
